### ISSUE TITLE
Add support for tapis resources in bdbag resolve-fetch

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/bdbag#1]
**Task:**
* Design and implement extension to bdbag CLI to allow fetching data from Tapis resources that are specified in the `fetch.txt` of an exported bag.
* Part of this will be implementing authentication support for Tapis in bdbag -- there is already an implementation for Globus that assumes the auth tokens are present in a config file.
* Part of this will be recognizing a given URL is a Tapis resource. This could be done via the `agave://` (or `tapis://`) scheme or via some regex match similar to WT lookup.

**Use case:**
* A user selects data files from a Tapis resource to include in their tale.  They export the tale via the BagIt exporter.  The exported bag `fetch.txt` contains URLs to the Tapis files.  When running `bdbag --resolve-fetch all` on the exported bag, the specified resources are materialized locally.

For example, given a `fetch.txt` that contains the following:
```
agave://www.designsafe-ci.org/api/public/files/media/published/designsafe.storage.published//PRJ-2280/WEST-SIM-DB/Site_Profile.bson  12345  data/data/Site_Profile.bson
```
Run `bdbag --resolve-fetch all` should cause the file to be copied to `data/data/Site_Profile.bson`

**See also (for WT specifics):**
* Where `fetch.txt` is generated in bagit exporter: https://github.com/whole-tale/girder_wholetale/blob/master/server/lib/exporters/bag.py#L144-L153
* How bdbag is used in conjunction with the exported tale: https://github.com/whole-tale/girder_wholetale/blob/master/server/lib/exporters/bag.py#L24-L40

**Completion criteria:**

* [ ] Written design document (Google doc) reviewed by dev team
* [ ] PR to this BDBag fork including unit tests and manual test case description
* [ ] PR reviewed and merged to WT fork (no need to worry about upstream right now)
